### PR TITLE
Fix JuMP and MOI interface

### LINKED ISSUE #21: MOI tests are broken
cc @blegat 

I'm not sure what broke, sorry!

### PR DESCRIPTION
**Pull request by odow**
Replacement for #22 

Closes #21 
Closes #22

### CODE REVIEW

**Comment by odow** [comment]
Is it intended that the Documentation has never been set up correctly?

**Comment by dpsanders** [comment]
Hah. Currently the "documentation" is the README, the Pluto notebook, the JuliaCon 2021 video, and the `examples` directory...

**Comment by dpsanders** [comment]
It's been a while since I've done this. What is required to set up proper docs?

https://github.com/dpsanders/SatisfiabilityInterface.jl/issues/26

**Comment by odow** [comment]
Well you don't really have any docs, so it's probably easiest just to delete the GitHub action.

**Comment by dpsanders** [comment]
@odow: It looks like we're testing on Julia 1.6 instead of Julia 1.7; would you be able to fix that in `Project.toml` and bump the version of this package to 0.1.1, please? 

What does Julia 1 test against?

**Comment by dpsanders** [comment]
Sure, good idea, thanks. Is that just deleting the `docs` part of `ci.yml`?

**Comment by odow** [comment]
> It looks like we're testing on Julia 1.6 instead of Julia 1.7

We test on both.

> would you be able to fix that in Project.toml

I bumped the minimum to Julia 1.6.

> bump the version of this package to 0.1.1, please?

Is this package even officially released? I couldn't find any evidence that it is, so until then, no need to bump the version number. It doesn't do anything.

> What does Julia 1 test against?

The latest minor release. At the moment, Julia 1.7, but soon, Julia 1.8.

> Is that just deleting the docs part of ci.yml?

https://github.com/dpsanders/SatisfiabilityInterface.jl/pull/27

**Comment by dpsanders** [comment]
No, it's not yet released, good point.

LGTM, thanks a lot!

**Pull request merged**
