### PR TITLE
Add CryptoMiniSat_jll

### PR DESCRIPTION
**Pull request by Wimmerer**
So this will require some modifications since I still needed ReversePropagation to run anything. But if I add ReversePropagation back this runs as expected. It'd be great to figure that out, get this merged, then I can work on Preferences.jl to allow different CryptoMinisat binaries and then define a good interface that individual solver packages can use via ccall rather than cmd.

E: Preferences should probably be in a CryptoMinisat.jl that implements this package's interface rather.

### CODE REVIEW

**Comment by dpsanders** [comment]
Fantastic, thanks!!

I don't think ReversePropagation should be needed for anything?

**Comment by dpsanders** [comment]
Could you bump the CI Julia version while you're at it, please?

**Comment by Wimmerer** [comment]
I couldn't run any of the tests without it.

**Comment by dpsanders** [comment]
Let's disable the MOI tests for the moment.

**Comment by dpsanders** [comment]
Going to merge this -- thanks a lot!

**Pull request merged**
